/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_UX;

import Logica.Anfitrion;
import Logica.DatosInmueble;
import Logica.Direccion;
import Logica.Inmueble;
import Logica.JavaBNB;
import Logica.Sesion;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

public class AddBuildings extends javax.swing.JPanel {

    String fotografia = "";

    /**
     * Creates new form AdminConsultarUsuarios
     */
    public AddBuildings() {
        initComponents();
        titleError.setVisible(false);
        descriptionError.setVisible(false);
        priceError.setVisible(false);
        guestError.setVisible(false);
        bedroomError.setVisible(false);
        bedError.setVisible(false);
        bathError.setVisible(false);
        serviceError.setVisible(false);
        bathError1.setVisible(false);
    }

    //Permite al usuario seleccionar una imagen cualquiera y devuelve su "File".
    public File openImage() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");
        fileChooser.setAcceptAllFileFilterUsed(false); // Deshabilitar la opción "Todos los archivos"
        fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif", "bmp"));

        int result = fileChooser.showOpenDialog(null); // Mostrar el diálogo de seleccion y capturar la respuesta

        // Procesar la respuesta
        if (result == JFileChooser.APPROVE_OPTION) {
            return fileChooser.getSelectedFile();
        }
        return null; // No file was selected or the user cancelled
    }

    //Método para guardar la imagen introducida en los archivos del proyecto,en la carpeta "fotosinmuebles".
    //Devuelve el String con la ruta a la imagen guardada.
    public String saveImage(File archivofoto) {
        String directoriodestino = "./src/main/resources/fotosinmuebles"; // Directorio de destino fijo
        //la ruta al archivo guardado será el directorio de la carpeta en el proyecto + el nombre de la imagen original
        Path pathdestino = Paths.get(directoriodestino, archivofoto.getName());

        try {
            // Asegurarse de que el directorio exista
            if (!Files.exists(Paths.get(directoriodestino))) {
                Files.createDirectories(Paths.get(directoriodestino));
            }

            // Copia el archivo al directorio especificado, reemplazando cualquier imagen dentro con la misma ruta
            Files.copy(archivofoto.toPath(), pathdestino, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("Imagen guardada en: " + pathdestino);
            return pathdestino.toString(); // Devuelve la ruta de la imagen como String
        } catch (IOException ex) {
            System.out.println("Error al guardar la imagen: " + ex.getMessage());
            return null; // Devuelve null si hay un error
        }
    }

    public void loadImage() {
        File fotoFile = openImage();
        if (fotoFile != null) {
            fotografia = saveImage(fotoFile);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        barraarriba = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        mainscr = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        data = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        guestLabel = new javax.swing.JLabel();
        bedroomLabel = new javax.swing.JLabel();
        bedLabel = new javax.swing.JLabel();
        bathLabel = new javax.swing.JLabel();
        servicesLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        titleTextField = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextPanel = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        servicesTextPane = new javax.swing.JTextPane();
        photoButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        cpTextField = new javax.swing.JTextField();
        createBuildingButton = new javax.swing.JButton();
        titleError = new javax.swing.JLabel();
        priceError = new javax.swing.JLabel();
        descriptionError = new javax.swing.JLabel();
        bedroomError = new javax.swing.JLabel();
        guestError = new javax.swing.JLabel();
        bathError = new javax.swing.JLabel();
        bedError = new javax.swing.JLabel();
        serviceError = new javax.swing.JLabel();
        guestSpinner = new javax.swing.JSpinner();
        bedroomSpinner = new javax.swing.JSpinner();
        bedSpinner = new javax.swing.JSpinner();
        bathSpinner = new javax.swing.JSpinner();
        bathError1 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 250, 248));

        barraarriba.setBackground(new java.awt.Color(255, 250, 248));
        barraarriba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraarriba.setLayout(new java.awt.GridBagLayout());

        logo.setBackground(new java.awt.Color(255, 153, 153));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.setDefaultCapable(false);
        logo.setFocusPainted(false);
        logo.setFocusable(false);
        logo.setRequestFocusEnabled(false);
        logo.setRolloverEnabled(false);
        logo.setVerifyInputWhenFocusTarget(false);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -35;
        gridBagConstraints.ipady = -32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 52, 12, 0);
        barraarriba.add(logo, gridBagConstraints);

        logoLabel.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 90, 95));
        logoLabel.setText("JavaBNB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        barraarriba.add(logoLabel, gridBagConstraints);

        mainscr.setBackground(new java.awt.Color(255, 90, 95));
        mainscr.setForeground(new java.awt.Color(255, 255, 255));
        mainscr.setText("Volver");
        mainscr.setBorderPainted(false);
        mainscr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainscr.setPreferredSize(new java.awt.Dimension(80, 30));
        mainscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscrActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 561, 0, 50);
        barraarriba.add(mainscr, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 90, 95));
        jLabel3.setText("¡Añade algún inmueble!");

        jLabel1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 90, 95));
        jLabel1.setText("Recuerda introducir todos los datos y no dejar nada vacío");

        data.setBackground(new java.awt.Color(255, 250, 248));
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        data.setMaximumSize(new java.awt.Dimension(1000, 1000));
        data.setPreferredSize(new java.awt.Dimension(600, 520));
        data.setRequestFocusEnabled(false);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleLabel.setText("Título:");

        typeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeLabel.setText("Tipo:");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionLabel.setText("Descripción:");

        photoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        photoLabel.setText("Fotografía:");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceLabel.setText("Precio por noche:");

        guestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guestLabel.setText("Máximo de huéspedes:");

        bedroomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bedroomLabel.setText("Nº de habitaciones:");

        bedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bedLabel.setText("Nº de camas:");

        bathLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bathLabel.setText("Nº de baños:");

        servicesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        servicesLabel.setText("Servicios:");

        typeComboBox.setBackground(new java.awt.Color(255, 90, 95));
        typeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento" }));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 50));

        titleTextField.setMinimumSize(new java.awt.Dimension(300, 50));
        titleTextField.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane2.setViewportView(titleTextField);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 50));

        descriptionTextPanel.setMinimumSize(new java.awt.Dimension(300, 50));
        descriptionTextPanel.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane3.setViewportView(descriptionTextPanel);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 50));

        servicesTextPane.setMinimumSize(new java.awt.Dimension(300, 50));
        servicesTextPane.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane4.setViewportView(servicesTextPane);

        photoButton.setBackground(new java.awt.Color(255, 90, 95));
        photoButton.setForeground(new java.awt.Color(255, 255, 255));
        photoButton.setText("Añadir fotografía");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberLabel.setText("Número:");

        streetLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        streetLabel.setText("Calle:");

        streetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextFieldActionPerformed(evt);
            }
        });

        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityLabel.setText("Ciudad:");

        cpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpLabel.setText("Código Postal:");

        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });

        cpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextFieldActionPerformed(evt);
            }
        });

        createBuildingButton.setBackground(new java.awt.Color(255, 90, 95));
        createBuildingButton.setForeground(new java.awt.Color(255, 255, 255));
        createBuildingButton.setText("Crear inmueble");
        createBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBuildingButtonActionPerformed(evt);
            }
        });

        titleError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titleError.setText("No es válido o está vacío");

        priceError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        priceError.setText("Debe ser mayor a 0");

        descriptionError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        descriptionError.setText("No es válido o está vacío");

        bedroomError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bedroomError.setText("Debe ser mayor a 0");

        guestError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        guestError.setText("Debe ser mayor a 0");

        bathError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bathError.setText("Debe ser mayor a 0");

        bedError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bedError.setText("Debe ser mayor a 0");

        serviceError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        serviceError.setText("No es válido o está vacío");

        guestSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        guestSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bedroomSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bedroomSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bedSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bedSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bathSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bathSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bathError1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bathError1.setText("Por favor, añada una fotografía");

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
        data.setLayout(dataLayout);
        dataLayout.setHorizontalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bathLabel)
                            .addGroup(dataLayout.createSequentialGroup()
                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bedLabel)
                                    .addComponent(bedroomLabel)
                                    .addComponent(guestLabel)
                                    .addComponent(priceLabel)
                                    .addComponent(photoLabel)
                                    .addComponent(servicesLabel)
                                    .addComponent(numberLabel))
                                .addGap(26, 26, 26)
                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(descriptionError))
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(streetTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                    .addComponent(numberTextField))
                                                .addGap(85, 85, 85)
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cpLabel)
                                                    .addComponent(cityLabel)))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(titleError, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(dataLayout.createSequentialGroup()
                                            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(guestSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bedroomSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bedSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bathSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(priceTextField))
                                            .addGap(57, 57, 57)
                                            .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bedroomError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bathError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bedError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(guestError, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bathError1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(priceError)
                                                .addGap(94, 94, 94))))
                                    .addComponent(serviceError)))
                            .addComponent(titleLabel)
                            .addComponent(typeLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(streetLabel)))
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(createBuildingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        dataLayout.setVerticalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(titleLabel)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(2, 2, 2))
                    .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(descriptionLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetLabel)
                            .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabel)
                            .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionError)
                        .addGap(41, 41, 41)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpLabel)
                            .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceError)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestLabel)
                    .addComponent(guestError)
                    .addComponent(guestSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedroomLabel)
                    .addComponent(bedroomError)
                    .addComponent(bedroomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedLabel)
                    .addComponent(bedError)
                    .addComponent(bedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathLabel)
                    .addComponent(bathError)
                    .addComponent(bathSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bathError1))
                .addGap(24, 24, 24)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servicesLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serviceError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(createBuildingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(barraarriba, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(barraarriba, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    //Al pulsar el botón de crear inmueble, se validarán todos los datos
    // introducidos y se mostrarán los respectivos mensajes de error si algún
    //dato no fuera válido. Si el usuario no ha seleccionado ninguna
    //fotografía, se llamará al método para añadirla de forma automática.
    private void createBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBuildingButtonActionPerformed
        Anfitrion anfitrion = (Anfitrion) Sesion.devolverCliente();
        if (anfitrion == null) {
            JOptionPane.showMessageDialog(this, "Error: el usuario actual no es un anfitrión válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String titulo = titleTextField.getText();
        String descripcion = descriptionTextPanel.getText();
        String calle = streetTextField.getText();
        String numero = numberTextField.getText();
        String ciudad = cityTextField.getText();
        String cp = cpTextField.getText();
        String tipo = (String) typeComboBox.getSelectedItem();
        double precio = 0;
        int huespedes = (int) guestSpinner.getValue();
        int habitaciones = (int) bedroomSpinner.getValue();
        int camas = (int) bedSpinner.getValue();
        int baños = (int) bathSpinner.getValue();
        String servicios = servicesTextPane.getText();
        boolean valido = true;

        // Validar título
        if (titulo.isEmpty()) {
            titleError.setVisible(true);
            valido = false;
        } else {
            titleError.setVisible(false);
        }

        // Validar fotografía
        if (fotografia == null || fotografia.isEmpty()) {
            loadImage();
            if (fotografia == null || fotografia.isEmpty()) {
                bathError1.setVisible(true);
                valido = false;
            } else {
                bathError1.setVisible(false);
            }
        }

        // Validar descripción
        if (descripcion.isEmpty()) {
            descriptionError.setVisible(true);
            valido = false;
        } else {
            descriptionError.setVisible(false);
        }

        // Validar calle. "calle.matches(".*\\d.*") evalúa si la cadena ciudad contiene algún número.
        if (calle.isEmpty() || calle.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "La calle no puede estar vacía ni contener números.", "Error en la calle", JOptionPane.WARNING_MESSAGE);
            valido = false;
        }

        // Validar número
        int numeroInt = 0;
        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La casilla del número del inmueble es necesaria", "Falta el número", JOptionPane.WARNING_MESSAGE);
            valido = false;
        } else {
            try {
                numeroInt = Integer.parseInt(numero);
                if (numeroInt <= 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                valido = false;
                JOptionPane.showMessageDialog(this, "El número del inmueble debe ser un número entero mayor que 0.", "Error de número", JOptionPane.WARNING_MESSAGE);
            }
        }

        // Validar ciudad. "ciudad.matches(".*\\d.*") evalúa si la cadena ciudad contiene algún número.
        if (ciudad.isEmpty() || ciudad.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "La ciudad no puede estar vacía ni contener números.", "Error en la ciudad", JOptionPane.WARNING_MESSAGE);
            valido = false;
        }

        // Validar código postal
        int cpInt = 0;
        if (cp.isEmpty() || cp.length() != 5) {
            JOptionPane.showMessageDialog(this, "El código postal debe tener 5 caracteres exactamente.", "Error del código postal", JOptionPane.WARNING_MESSAGE);
            valido = false;
        } else {
            try {
                cpInt = Integer.parseInt(cp);
            } catch (NumberFormatException e) {
                valido = false;
                JOptionPane.showMessageDialog(this, "El código postal debe ser un número entero.", "Error del código postal", JOptionPane.WARNING_MESSAGE);
            }
        }

        // Validar precio
        try {
            String priceText = priceTextField.getText().trim();

            // "priceText.matches(".*\\d.*") evalúa si el precio es un número con hasta dos decimales, separado por un punto.
            // \\d+ significa que la "cadena" debe empezar por uno o más números
            // El resto indica que la cadena puede o no tener más digitos decimales (hasta 2)
            if (priceText.isEmpty() || !priceText.matches("\\d+(\\.\\d{1,2})?")) {
                throw new NumberFormatException("El precio debe ser un número válido con hasta dos decimales.");
            }
            precio = Double.parseDouble(priceText);

            if (precio <= 0) {
                throw new NumberFormatException("El precio debe ser mayor que 0.");
            }
            priceError.setVisible(false);

        } catch (NumberFormatException e) {
            priceError.setVisible(true);
            valido = false;
            JOptionPane.showMessageDialog(this, "Introduce un precio válido mayor que 0. \nRecuerda usar un punto para los decimales (ej. 233.35).", "Error del precio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar huéspedes
        if (huespedes <= 0) {
            guestError.setVisible(true);
            valido = false;
        } else {
            guestError.setVisible(false);
        }

        // Validar habitaciones
        if (habitaciones <= 0) {
            bedroomError.setVisible(true);
            valido = false;
        } else {
            bedroomError.setVisible(false);
        }

        // Validar camas
        if (camas <= 0) {
            bedError.setVisible(true);
            valido = false;
        } else {
            bedError.setVisible(false);
        }

        // Validar baños
        if (baños <= 0) {
            bathError.setVisible(true);
            valido = false;
        } else {
            bathError.setVisible(false);
        }

        // Validar servicios
        if (servicios.isEmpty()) {
            serviceError.setVisible(true);
            valido = false;
        } else {
            serviceError.setVisible(false);
        }

        if (valido) {
            DatosInmueble datos = new DatosInmueble(huespedes, habitaciones, camas, baños);
            Direccion direccion = new Direccion(calle, numero, cp, ciudad);
            Inmueble inmueble = new Inmueble(titulo, descripcion, direccion, datos, tipo, precio, fotografia, servicios, anfitrion);
            boolean inmuebleValido = JavaBNB.añadirInmueble(inmueble);
            if (inmuebleValido) {
                JOptionPane.showMessageDialog(this, "El inmueble se ha creado correctamente, se ha añadido a la lista de inmuebles.", "Inmueble creado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El inmueble ya existe, no aceptamos inmuebles duplicados.", "Inmueble ya existente", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_createBuildingButtonActionPerformed

    private void cpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextFieldActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
        File f = openImage();
        if (f != null) {
            fotografia = saveImage(f);
        } else {
            System.out.println("no existe la ruta");
        }

    }//GEN-LAST:event_photoButtonActionPerformed

    private void mainscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscrActionPerformed
        App.loadMainScreen();
    }//GEN-LAST:event_mainscrActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraarriba;
    private javax.swing.JLabel bathError;
    private javax.swing.JLabel bathError1;
    private javax.swing.JLabel bathLabel;
    private javax.swing.JSpinner bathSpinner;
    private javax.swing.JLabel bedError;
    private javax.swing.JLabel bedLabel;
    private javax.swing.JSpinner bedSpinner;
    private javax.swing.JLabel bedroomError;
    private javax.swing.JLabel bedroomLabel;
    private javax.swing.JSpinner bedroomSpinner;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JTextField cpTextField;
    private javax.swing.JButton createBuildingButton;
    private javax.swing.JPanel data;
    private javax.swing.JLabel descriptionError;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextPane descriptionTextPanel;
    private javax.swing.JLabel guestError;
    private javax.swing.JLabel guestLabel;
    private javax.swing.JSpinner guestSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logo;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton mainscr;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel priceError;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel serviceError;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JTextPane servicesTextPane;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JLabel titleError;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextPane titleTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
