/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_UX;

import Logica.DatosInmueble;
import Logica.Direccion;
import Logica.Inmueble;
import Logica.JavaBNB;
import javax.swing.*;
import Logica.Validacion;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

public class AddBuildings extends javax.swing.JPanel {

    String fotografia = "";

    /**
     * Creates new form AdminConsultarUsuarios
     */
    public AddBuildings() {
        initComponents();
        titleError.setVisible(false);
        descriptionError.setVisible(false);
        priceError.setVisible(false);
        guestError.setVisible(false);
        bedroomError.setVisible(false);
        bedError.setVisible(false);
        bathError.setVisible(false);
        serviceError.setVisible(false);
        bathError1.setVisible(false);
    }

    public File openImage() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif", "bmp"));

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            return fileChooser.getSelectedFile();
        }
        return null; // No file was selected or the user cancelled.
    }

    public String saveImage(File sourceFile) {
        String destinationDirectory = "./src/main/resources/fotosinmuebles"; // Directorio de destino fijo
        Path destinationPath = Paths.get(destinationDirectory, sourceFile.getName());

        try {
            // Asegúrate de que el directorio exista
            if (!Files.exists(Paths.get(destinationDirectory))) {
                Files.createDirectories(Paths.get(destinationDirectory));
            }

            // Copia el archivo al directorio especificado
            Files.copy(sourceFile.toPath(), destinationPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("Imagen guardada en: " + destinationPath);
            return destinationPath.toString(); // Devuelve la ruta de la imagen como String
        } catch (IOException ex) {
            System.out.println("Error al guardar la imagen: " + ex.getMessage());
            return null; // Devuelve null si hay un error
        }
    }

    public void loadImage() {
        File selectedFile = openImage();
        if (selectedFile != null) {
            fotografia = saveImage(selectedFile);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        barraarriba = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        mainscr = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        data = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        guestLabel = new javax.swing.JLabel();
        bedroomLabel = new javax.swing.JLabel();
        bedLabel = new javax.swing.JLabel();
        bathLabel = new javax.swing.JLabel();
        servicesLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        titleTextField = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextPanel = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        servicesTextPane = new javax.swing.JTextPane();
        photoButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cpLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        cpTextField = new javax.swing.JTextField();
        createBuildingButton = new javax.swing.JButton();
        titleError = new javax.swing.JLabel();
        priceError = new javax.swing.JLabel();
        descriptionError = new javax.swing.JLabel();
        bedroomError = new javax.swing.JLabel();
        guestError = new javax.swing.JLabel();
        bathError = new javax.swing.JLabel();
        bedError = new javax.swing.JLabel();
        serviceError = new javax.swing.JLabel();
        guestSpinner = new javax.swing.JSpinner();
        bedroomSpinner = new javax.swing.JSpinner();
        bedSpinner = new javax.swing.JSpinner();
        bathSpinner = new javax.swing.JSpinner();
        bathError1 = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();

        jPanel3.setBackground(new java.awt.Color(255, 250, 248));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        barraarriba.setBackground(new java.awt.Color(255, 250, 248));
        barraarriba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barraarriba.setLayout(new java.awt.GridBagLayout());

        logo.setBackground(new java.awt.Color(255, 153, 153));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.setDefaultCapable(false);
        logo.setFocusPainted(false);
        logo.setFocusable(false);
        logo.setRequestFocusEnabled(false);
        logo.setRolloverEnabled(false);
        logo.setVerifyInputWhenFocusTarget(false);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -35;
        gridBagConstraints.ipady = -32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 52, 12, 0);
        barraarriba.add(logo, gridBagConstraints);

        logoLabel.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 90, 95));
        logoLabel.setText("JavaBNB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        barraarriba.add(logoLabel, gridBagConstraints);

        mainscr.setBackground(new java.awt.Color(255, 90, 95));
        mainscr.setForeground(new java.awt.Color(255, 255, 255));
        mainscr.setText("Volver");
        mainscr.setBorderPainted(false);
        mainscr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainscr.setPreferredSize(new java.awt.Dimension(80, 30));
        mainscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscrActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 561, 0, 50);
        barraarriba.add(mainscr, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(barraarriba, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 90, 95));
        jLabel3.setText("¡Añade algún inmueble!");

        jLabel1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 90, 95));
        jLabel1.setText("Recuerda introducir todos los datos y no dejar nada vacío");

        data.setBackground(new java.awt.Color(255, 250, 248));
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        data.setMaximumSize(new java.awt.Dimension(1000, 1000));
        data.setPreferredSize(new java.awt.Dimension(600, 520));
        data.setRequestFocusEnabled(false);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleLabel.setText("Título:");

        typeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeLabel.setText("Tipo:");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionLabel.setText("Descripción:");

        photoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        photoLabel.setText("Fotografía:");

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceLabel.setText("Precio por noche:");

        guestLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guestLabel.setText("Máximo de huéspedes:");

        bedroomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bedroomLabel.setText("Nº de habitaciones:");

        bedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bedLabel.setText("Nº de camas:");

        bathLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bathLabel.setText("Nº de baños:");

        servicesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        servicesLabel.setText("Servicios:");

        typeComboBox.setBackground(new java.awt.Color(255, 90, 95));
        typeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento" }));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 50));

        titleTextField.setMinimumSize(new java.awt.Dimension(300, 50));
        titleTextField.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane2.setViewportView(titleTextField);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 50));

        descriptionTextPanel.setMinimumSize(new java.awt.Dimension(300, 50));
        descriptionTextPanel.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane3.setViewportView(descriptionTextPanel);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 50));

        servicesTextPane.setMinimumSize(new java.awt.Dimension(300, 50));
        servicesTextPane.setPreferredSize(new java.awt.Dimension(300, 60));
        jScrollPane4.setViewportView(servicesTextPane);

        photoButton.setBackground(new java.awt.Color(255, 90, 95));
        photoButton.setForeground(new java.awt.Color(255, 255, 255));
        photoButton.setText("Añadir fotografía");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberLabel.setText("Número:");

        streetLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        streetLabel.setText("Calle:");

        streetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextFieldActionPerformed(evt);
            }
        });

        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityLabel.setText("Ciudad:");

        cpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpLabel.setText("Código Postal:");

        cityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextFieldActionPerformed(evt);
            }
        });

        cpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpTextFieldActionPerformed(evt);
            }
        });

        createBuildingButton.setBackground(new java.awt.Color(255, 90, 95));
        createBuildingButton.setForeground(new java.awt.Color(255, 255, 255));
        createBuildingButton.setText("Crear inmueble");
        createBuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBuildingButtonActionPerformed(evt);
            }
        });

        titleError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        titleError.setText("No es válido o está vacío");

        priceError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        priceError.setText("Debe ser mayor a 0");

        descriptionError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        descriptionError.setText("No es válido o está vacío");

        bedroomError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bedroomError.setText("Debe ser mayor a 0");

        guestError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        guestError.setText("Debe ser mayor a 0");

        bathError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bathError.setText("Debe ser mayor a 0");

        bedError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bedError.setText("Debe ser mayor a 0");

        serviceError.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        serviceError.setText("No es válido o está vacío");

        guestSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        guestSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bedroomSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bedroomSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bedSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bedSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bathSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        bathSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        bathError1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bathError1.setText("Por favor, añada una fotografía");

        priceSpinner.setMinimumSize(new java.awt.Dimension(113, 27));
        priceSpinner.setPreferredSize(new java.awt.Dimension(113, 27));

        javax.swing.GroupLayout dataLayout = new javax.swing.GroupLayout(data);
        data.setLayout(dataLayout);
        dataLayout.setHorizontalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bathLabel)
                            .addGroup(dataLayout.createSequentialGroup()
                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bedLabel)
                                    .addComponent(bedroomLabel)
                                    .addComponent(guestLabel)
                                    .addComponent(priceLabel)
                                    .addComponent(photoLabel)
                                    .addComponent(servicesLabel)
                                    .addComponent(numberLabel))
                                .addGap(26, 26, 26)
                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(descriptionError))
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(streetTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                    .addComponent(numberTextField))
                                                .addGap(85, 85, 85)
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cpLabel)
                                                    .addComponent(cityLabel)))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(titleError, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(guestSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bedroomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bathSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(57, 57, 57)
                                                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bedroomError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(bathError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(bedError, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(guestError, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceError))
                                    .addGroup(dataLayout.createSequentialGroup()
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(dataLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bathError1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(priceError)
                                                .addGap(94, 94, 94))))))
                            .addComponent(titleLabel)
                            .addComponent(typeLabel)
                            .addComponent(descriptionLabel)
                            .addComponent(streetLabel)))
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(createBuildingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        dataLayout.setVerticalGroup(
            dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(titleLabel)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(2, 2, 2))
                    .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataLayout.createSequentialGroup()
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(descriptionLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetLabel)
                            .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabel)
                            .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionError)
                        .addGap(41, 41, 41)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpLabel)
                            .addComponent(cpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceError)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestLabel)
                    .addComponent(guestError)
                    .addComponent(guestSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedroomLabel)
                    .addComponent(bedroomError)
                    .addComponent(bedroomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedLabel)
                    .addComponent(bedError)
                    .addComponent(bedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathLabel)
                    .addComponent(bathError)
                    .addComponent(bathSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bathError1))
                .addGap(24, 24, 24)
                .addGroup(dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servicesLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(createBuildingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 119, 0);
        jPanel3.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBuildingButtonActionPerformed

        String titulo = titleTextField.getText();
        String descripcion = descriptionTextPanel.getText();
        String calle = streetTextField.getText();
        String numero = numberTextField.getText();
        String ciudad = cityTextField.getText();
        String cp = cpTextField.getText();
        String tipo = (String) typeComboBox.getSelectedItem();

        //TODO: hacer formatted field en vez de priceSpinner. mejorar las validaciones (por ej puedes poner una letra como numero)
        double precio = ((Integer) priceSpinner.getValue()).doubleValue();
        int huespedes = (int) guestSpinner.getValue();
        int habitaciones = (int) bedroomSpinner.getValue();
        int camas = (int) bedSpinner.getValue();
        int baños = (int) bathSpinner.getValue();
        String servicios = servicesTextPane.getText();

        boolean valido = true;

        if (titulo.isEmpty()) {
            titleError.setVisible(true);
            valido = false;

        } else {
            titleError.setVisible(false);
        }

        if (fotografia == null || fotografia.isEmpty()) {
            loadImage(); // Llama al método loadImage() para cargar la imagen
            if (fotografia == null || fotografia.isEmpty()) { // Verifica si la carga de la imagen fue exitosa
                bathError1.setVisible(true);
                valido = false;
            } else {
                System.out.println(fotografia);
                bathError1.setVisible(false);
            }
        }

        if (descripcion.isEmpty()) {
            descriptionError.setVisible(true);
            valido = false;
        } else {
            descriptionError.setVisible(false);
        }

        if (!Validacion.validarNombre(ciudad)) {
            JOptionPane.showMessageDialog(this, "Existe algún error con la ciudad, puede que esté vacía o que el formato no sea válido", "Error con la ciudad", JOptionPane.WARNING_MESSAGE);
            valido = false;
        }

        if (!Validacion.validarNombre(calle)) {
            JOptionPane.showMessageDialog(this, "La casilla de la calle del inmueble es necesaria", "Falta la calle", JOptionPane.WARNING_MESSAGE);
            valido = false;
        }

        boolean numeroo = false;
        int numeroInt = 0;
        if (!numero.isEmpty()) {
            try {
                numeroInt = Integer.parseInt(numero);
                numeroo = true;
            } catch (NumberFormatException e) {
                valido = false;
                JOptionPane.showMessageDialog(this, "El número del inmueble debe ser un número entero.", "Error de número", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La casilla del número del inmueble es necesaria", "Falta el número", JOptionPane.WARNING_MESSAGE);
            valido = false;

        }
        boolean cpp = false;
        int cpInt = 0;
        if (!cp.isEmpty() && cp.length() == 5) {
            try {
                cpInt = Integer.parseInt(cpTextField.getText());
                cpp = true;
            } catch (NumberFormatException e) {
                valido = false;
                JOptionPane.showMessageDialog(this, "El código postal tiene que ser un número entero.", "Error del código postal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            valido = false;
            valido = false;
            JOptionPane.showMessageDialog(this, "El código postal debe tener 5 carácteres exactamente", "Error del código postal", JOptionPane.WARNING_MESSAGE);
        }

        if (precio <= 0) {
            priceError.setVisible(true);
            valido = false;

        } else {
            priceError.setVisible(false);
        }

        if (huespedes <= 0) {
            guestError.setVisible(true);
            valido = false;

        } else {
            guestError.setVisible(false);
        }

        if (habitaciones <= 0) {
            bedroomError.setVisible(true);
            valido = false;

        } else {
            bedroomError.setVisible(false);
        }

        if (camas <= 0) {
            bedError.setVisible(true);
            valido = false;

        } else {
            bedError.setVisible(false);
        }

        if (baños <= 0) {
            bathError.setVisible(true);
            valido = false;

        } else {
            bathError.setVisible(false);
        }

        if (servicios.isEmpty()) {
            serviceError.setVisible(true);
            valido = false;
        } else {
            serviceError.setVisible(false);

        }

        if (valido) {
            DatosInmueble datos = new DatosInmueble(huespedes, habitaciones, camas, baños);
            Direccion direccion = new Direccion(calle, numero, cp, ciudad);
            Inmueble inmueble = new Inmueble(titulo, descripcion, direccion, datos, tipo, precio, fotografia, servicios);
            boolean inmuebleValido = JavaBNB.añadirInmueble(inmueble);
            if (inmuebleValido) {
                JOptionPane.showMessageDialog(this, "El inmueble se ha creado correctamente, se ha añadido a la lista de inmuebles.", "Inmueble creado", JOptionPane.WARNING_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "El inmueble ya existe, no aceptamos inmuebles duplicados.", "Inmueble ya existente", JOptionPane.WARNING_MESSAGE);

            }
            return;
        }
    }//GEN-LAST:event_createBuildingButtonActionPerformed

    private void cpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextFieldActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
        File f = openImage();
        if (f != null) {
            fotografia = saveImage(f);
        } else {
            System.out.println("no existe la ruta");
        }

    }//GEN-LAST:event_photoButtonActionPerformed

    private void mainscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscrActionPerformed
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla mainscreenhost");
    }//GEN-LAST:event_mainscrActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraarriba;
    private javax.swing.JLabel bathError;
    private javax.swing.JLabel bathError1;
    private javax.swing.JLabel bathLabel;
    private javax.swing.JSpinner bathSpinner;
    private javax.swing.JLabel bedError;
    private javax.swing.JLabel bedLabel;
    private javax.swing.JSpinner bedSpinner;
    private javax.swing.JLabel bedroomError;
    private javax.swing.JLabel bedroomLabel;
    private javax.swing.JSpinner bedroomSpinner;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JTextField cpTextField;
    private javax.swing.JButton createBuildingButton;
    private javax.swing.JPanel data;
    private javax.swing.JLabel descriptionError;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextPane descriptionTextPanel;
    private javax.swing.JLabel guestError;
    private javax.swing.JLabel guestLabel;
    private javax.swing.JSpinner guestSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logo;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton mainscr;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel priceError;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JLabel serviceError;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JTextPane servicesTextPane;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JLabel titleError;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextPane titleTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
