/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_UX;

import Logica.Particular;
import Logica.Reserva;
import Logica.Sesion;
import Logica.Tarjeta;
import Logica.Validacion;
import java.time.LocalDate;
import java.util.ArrayList;

public class ClientProfile extends javax.swing.JPanel {

    public ArrayList<ReservasView> reservasicon;
    public Particular particular;

    /**
     * Creates new form UserProfile
     */
    public ClientProfile() {
        initComponents();
        errorLabel1.setVisible(false);
        requirementsLabel.setVisible(false);
        emailTextField.setEditable(false);
        clave.setEditable(false);
        tlfTextField.setEditable(false);
        promocodeTextField.setEditable(false);
        CCTextField.setEditable(false);
        dayTextField.setEditable(false);
        monthTextField.setEditable(false);
        yearTextField.setEditable(false);
        moneyTextField.setEditable(false);
        cvvTextField.setEditable(false);

    }

    public void actualizar() {
        if (Sesion.user != null) {
            // Establecer los campos de texto con la información del usuario actual
            dniTextField.setText(Sesion.user.getDni());
            username.setText(Sesion.user.getNombre().toUpperCase());
            emailTextField.setText(Sesion.user.getCorreo());
            clave.setText(Sesion.user.getClave());
            tlfTextField.setText(Sesion.user.getTelefono());
            if (Sesion.esUsuarioVip()) {
                promocodeTextField.setText("JAVABNB2024");
            } else {
                promocodeTextField.setText("    ");
            }

            Tarjeta tarjeta = ((Particular) Sesion.user).getTarjetaCredito();
            if (tarjeta != null) {
                CCTextField.setText(tarjeta.getNumeroTarjeta());
                LocalDate fechaCaducidad = tarjeta.getFechaCaducidad();
                dayTextField.setText(String.valueOf(fechaCaducidad.getDayOfMonth()));
                monthTextField.setText(String.valueOf(fechaCaducidad.getMonthValue()));
                yearTextField.setText(String.valueOf(fechaCaducidad.getYear()));
                cvvTextField.setText(tarjeta.getCvv());
                moneyTextField.setText(String.valueOf(tarjeta.getSaldo()));
            }

            reservasicon = new ArrayList<>();
            insertarReservas();

        }
    }

    public void insertarReservas() {

        deleteBuildings(); // Borra cualquier widget de reserva existente antes de insertar nuevos

        int fila = 0;
        //tamaño ventana widget=[225, 229]
        int x = 50; //valor de prueba
        for (Reserva reserva : (((Particular) Sesion.user).getReservas())) {
            if (x >= 941) { //tamaño del panel de ancho
                fila += 229;
                x = 50;
            }
            ReservasView iconoreserva = new ReservasView();
            iconoreserva.init(reserva);

            reservasicon.add(iconoreserva);
            reservasContainer.add(iconoreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, fila, -1, -1));  //méto comp, java.lang.Object constr); do addLayoutComponent(java.awt.Component comp, java.lang.Object constr);  Adds the specified component to the layout, using the specified constraint object.

            x += 400; //valor de prueba
            System.out.println(reserva.toString());
        }
        reservasContainer.revalidate(); // Actualiza el contenedor para mostrar los cambios
        reservasContainer.repaint();   // Repinta el contenedor para asegurar que los cambios sean visibles
    }

    public void deleteBuildings() {
        for (ReservasView rv : reservasicon) {
            this.reservasicon.remove(rv);
        }
        reservasicon.clear(); // Limpia la lista de widgets de edificios después de eliminarlos
        reservasContainer.revalidate(); // Actualiza el contenedor para mostrar los cambios
        reservasContainer.repaint();   // Repinta el contenedor para asegurar que los cambios sean visibles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        uppermenu = new javax.swing.JPanel();
        appname = new javax.swing.JLabel();
        logo = new javax.swing.JButton();
        logo1 = new javax.swing.JButton();
        mainscr = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        addMoneyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        errorLabel1 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        promocodeLabel = new javax.swing.JLabel();
        promocodeTextField = new javax.swing.JTextField();
        CCLabel = new javax.swing.JLabel();
        CCTextField = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        moneyLabel = new javax.swing.JLabel();
        moneyTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        userpfp = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        ParLabel = new javax.swing.JLabel();
        reservasLabel = new javax.swing.JLabel();
        reservasContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 250, 248));

        jPanel2.setBackground(new java.awt.Color(255, 250, 248));

        uppermenu.setBackground(new java.awt.Color(255, 250, 248));
        uppermenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uppermenu.setLayout(new java.awt.GridBagLayout());

        appname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        appname.setForeground(new java.awt.Color(255, 90, 95));
        appname.setText("JavaBNB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        uppermenu.add(appname, gridBagConstraints);

        logo.setBackground(new java.awt.Color(255, 153, 153));
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.setDefaultCapable(false);
        logo.setFocusPainted(false);
        logo.setFocusable(false);
        logo.setRequestFocusEnabled(false);
        logo.setRolloverEnabled(false);
        logo.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        uppermenu.add(logo, gridBagConstraints);

        logo1.setBackground(new java.awt.Color(255, 153, 153));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        logo1.setBorderPainted(false);
        logo1.setContentAreaFilled(false);
        logo1.setDefaultCapable(false);
        logo1.setFocusPainted(false);
        logo1.setFocusable(false);
        logo1.setRequestFocusEnabled(false);
        logo1.setRolloverEnabled(false);
        logo1.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -31;
        gridBagConstraints.ipady = -24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 101, 3, 0);
        uppermenu.add(logo1, gridBagConstraints);

        mainscr.setBackground(new java.awt.Color(255, 90, 95));
        mainscr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainscr.setForeground(new java.awt.Color(255, 255, 255));
        mainscr.setText("Volver");
        mainscr.setBorderPainted(false);
        mainscr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainscr.setPreferredSize(new java.awt.Dimension(80, 30));
        mainscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainscrActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 68, 0, 50);
        uppermenu.add(mainscr, gridBagConstraints);

        cerrarsesion.setBackground(new java.awt.Color(255, 90, 95));
        cerrarsesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarsesion.setText("Cerrar sesión");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 611, 0, 0);
        uppermenu.add(cerrarsesion, gridBagConstraints);

        addMoneyButton.setBackground(new java.awt.Color(255, 90, 95));
        addMoneyButton.setForeground(new java.awt.Color(255, 255, 255));
        addMoneyButton.setText("Añadir 50 euros");
        addMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.insets = new java.awt.Insets(23, 268, 0, 0);
        uppermenu.add(addMoneyButton, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));

        data.setBackground(new java.awt.Color(255, 250, 248));
        data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        data.setMaximumSize(new java.awt.Dimension(306, 307));
        data.setPreferredSize(new java.awt.Dimension(306, 400));
        data.setRequestFocusEnabled(false);
        data.setLayout(new java.awt.GridBagLayout());

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setText("Correo electrónico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 21, 0, 0);
        data.add(emailLabel, gridBagConstraints);

        dniLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dniLabel.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        data.add(dniLabel, gridBagConstraints);

        tlfLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tlfLabel.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        data.add(tlfLabel, gridBagConstraints);

        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passLabel.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 21, 0, 0);
        data.add(passLabel, gridBagConstraints);

        clave.setText("contraseña1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 191;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        data.add(clave, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 90, 95));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 202;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 286;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 67, 0, 0);
        data.add(jButton1, gridBagConstraints);

        emailTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 108;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 285;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 2, 0, 0);
        data.add(emailTextField, gridBagConstraints);

        dniTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 44;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 0, 0);
        data.add(dniTextField, gridBagConstraints);

        tlfTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 96;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        data.add(tlfTextField, gridBagConstraints);

        errorLabel1.setBackground(new java.awt.Color(255, 90, 95));
        errorLabel1.setForeground(new java.awt.Color(255, 90, 95));
        errorLabel1.setText("Alguno de los datos no cumple el formato requerido, o no es válido");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 478;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 62, 53);
        data.add(errorLabel1, gridBagConstraints);

        requirementsLabel.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una letra mayúscula, minúscula, dígitos y 8 caracteres de longitud");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 477;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        data.add(requirementsLabel, gridBagConstraints);

        promocodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        promocodeLabel.setText("Código promocional:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        data.add(promocodeLabel, gridBagConstraints);

        promocodeTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 202;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 0);
        data.add(promocodeTextField, gridBagConstraints);

        CCLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CCLabel.setText("Tarjeta de crédito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        data.add(CCLabel, gridBagConstraints);

        CCTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 56;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 433;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 152;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        data.add(CCTextField, gridBagConstraints);

        dayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayLabel.setText("Día:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        data.add(dayLabel, gridBagConstraints);

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthLabel.setText("Mes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 21, 0, 0);
        data.add(monthLabel, gridBagConstraints);

        yearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLabel.setText("Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 21, 0, 0);
        data.add(yearLabel, gridBagConstraints);

        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 0, 0);
        data.add(dayTextField, gridBagConstraints);

        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 9, 0, 0);
        data.add(monthTextField, gridBagConstraints);

        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        data.add(cvvTextField, gridBagConstraints);

        cvvLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cvvLabel.setText("CVV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 21, 0, 0);
        data.add(cvvLabel, gridBagConstraints);

        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        data.add(yearTextField, gridBagConstraints);

        moneyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moneyLabel.setText("Saldo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 21, 0, 0);
        data.add(moneyLabel, gridBagConstraints);

        moneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        data.add(moneyTextField, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 90, 95));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Editar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 202;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 286;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 67, 0, 0);
        data.add(jButton2, gridBagConstraints);

        userpfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (2).jpg"))); // NOI18N
        userpfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpfpActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        username.setForeground(new java.awt.Color(255, 90, 95));
        username.setText("XXXXXX");

        ParLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        ParLabel.setForeground(new java.awt.Color(102, 102, 102));
        ParLabel.setText("Cliente");

        reservasLabel.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        reservasLabel.setForeground(new java.awt.Color(255, 90, 95));
        reservasLabel.setText("Lista de reservas");
        reservasLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userpfp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(username))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(ParLabel)))
                .addGap(70, 70, 70)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservasLabel)
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userpfp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(username)
                        .addGap(14, 14, 14)
                        .addComponent(ParLabel))
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(reservasLabel)
                .addContainerGap())
        );

        reservasContainer.setMaximumSize(new java.awt.Dimension(941, 2147483647));
        reservasContainer.setMinimumSize(new java.awt.Dimension(941, 0));
        reservasContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uppermenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservasContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(uppermenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reservasContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userpfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpfpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ActionListener para el botón
        // Verificar el texto actual del botón
        if (jButton1.getText().equals("Editar datos")) {
            // Si el botón está en modo "Editar datos"
            // Establecer los campos de texto como editables
            emailTextField.setEditable(true);
            clave.setEditable(true);
            tlfTextField.setEditable(true);
            if (Sesion.esUsuarioVip()) {

                promocodeTextField.setEditable(false);
            } else {
                promocodeTextField.setEditable(true);
            }
            // Cambiar el texto del botón a "Aceptar"
            jButton1.setText("Aceptar");
        } else {
            // Si el botón está en modo "Aceptar"
            // Establecer los campos de texto como no editables
            emailTextField.setEditable(false);
            clave.setEditable(false);
            tlfTextField.setEditable(false);
            promocodeTextField.setEditable(false);

            jButton1.setText("Editar datos");

            String email = emailTextField.getText();
            String password = clave.getText();
            String telefono = tlfTextField.getText();
            String promocode = promocodeTextField.getText();

            boolean valido = true;

            // Verificar el correo electrónico
            if (!Validacion.validarEmail(email)) {
                errorLabel1.setVisible(true);
                emailTextField.setText("");
                valido = false;
            } // Verificar la contraseña
            else if (!Validacion.validarContraseña(password)) {
                errorLabel1.setVisible(true);
                clave.setText("");
                valido = false;
            } // Verificar el teléfono
            else if (!Validacion.validarTelefono(telefono)) {
                errorLabel1.setVisible(true);
                tlfTextField.setText("");
                valido = false;
            }

            // Verificar el código promocional
            if (!Validacion.validarPromocode(promocode)) {
                errorLabel1.setVisible(true);
                promocodeTextField.setText("");
                valido = false;
            } else {
                errorLabel1.setVisible(false);
            }

            if (valido) {
                errorLabel1.setVisible(false);

                Sesion.user.setCorreo(email);
                Sesion.user.setTelefono(telefono);
                Sesion.user.setClave(password);

                // Verificar y actualizar el estado VIP
                if (Sesion.hacerVipSiPromocodeValido(promocode)) {
                    System.out.println("El usuario ha sido actualizado a VIP.");
                }

                System.out.println(Sesion.user.toString());
            } else {
                errorLabel1.setVisible(false);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void moneyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTextFieldActionPerformed

    private void mainscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainscrActionPerformed
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla mainscreenclient");
    }//GEN-LAST:event_mainscrActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        Sesion.cerrarSesion();
        Aplicacion.cardLayout.show(Aplicacion.cards, "Pantalla login");
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyButtonActionPerformed
        // Verifica si el usuario actual es un Particular
        if (Sesion.user instanceof Particular) {
            Particular particular = (Particular) Sesion.user;
            Tarjeta tarjeta = particular.getTarjetaCredito();

            // Verifica si el Particular tiene una tarjeta de crédito asociada
            if (tarjeta != null) {
                // Incrementa el saldo de la tarjeta en 50 euros
                tarjeta.incrementarSaldo(50.0);
                moneyTextField.setText(String.valueOf(tarjeta.getSaldo()));
                // Actualiza la interfaz de usuario para mostrar el nuevo saldo (si tienes una etiqueta o campo de texto para el saldo)
                // saldoLabel.setText("Saldo: " + tarjeta.getSaldo());  // Actualiza el label del saldo si existe
                System.out.println("Saldo añadido. Nuevo saldo: " + tarjeta.getSaldo());
            } else {
                System.out.println("El usuario no tiene una tarjeta de crédito asociada.");
            }
        } else {
            System.out.println("El usuario actual no es un cliente particular.");

        }

    }//GEN-LAST:event_addMoneyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTextField CCTextField;
    private javax.swing.JLabel ParLabel;
    private javax.swing.JButton addMoneyButton;
    private javax.swing.JLabel appname;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JPasswordField clave;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JPanel data;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logo;
    private javax.swing.JButton logo1;
    private javax.swing.JButton mainscr;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel promocodeLabel;
    private javax.swing.JTextField promocodeTextField;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JPanel reservasContainer;
    private javax.swing.JLabel reservasLabel;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JPanel uppermenu;
    private javax.swing.JLabel username;
    private javax.swing.JButton userpfp;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
