
package UI_UX;

import Logica.*;
import UI_UX.ClientProfile;

// Panel que permite al usuario iniciar sesión.

public class Login extends javax.swing.JPanel {

    public Login() {
        initComponents();
        errorLabel.setVisible(false);
    }

    private void resetText() {
        emailTextField.setText("");
        passwordTextField.setText("");
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        space5 = new javax.swing.JLabel();
        space6 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        statementLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        privacypolicyLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 250, 248));
        setMaximumSize(new java.awt.Dimension(888, 676));
        setMinimumSize(new java.awt.Dimension(888, 676));
        setPreferredSize(new java.awt.Dimension(888, 676));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));
        jPanel1.setMaximumSize(new java.awt.Dimension(888, 676));
        jPanel1.setMinimumSize(new java.awt.Dimension(888, 676));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 90, 95));
        titleLabel.setText("¡Bienvenid@ a javabnb!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 209, 0, 210);
        jPanel1.add(titleLabel, gridBagConstraints);

        photoLabel.setBackground(new java.awt.Color(255, 90, 95));
        photoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        photoLabel.setBorderPainted(false);
        photoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        photoLabel.setDefaultCapable(false);
        photoLabel.setFocusPainted(false);
        photoLabel.setFocusable(false);
        photoLabel.setRequestFocusEnabled(false);
        photoLabel.setRolloverEnabled(false);
        photoLabel.setVerifyInputWhenFocusTarget(false);
        photoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoLabelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 99, 0, 0);
        jPanel1.add(photoLabel, gridBagConstraints);

        loginLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginLabel.setText("INICIO DE SESIÓN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 56, 0, 0);
        jPanel1.add(loginLabel, gridBagConstraints);

        userLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(102, 102, 102));
        userLabel.setText("Correo *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 209, 0, 0);
        jPanel1.add(userLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(102, 102, 102));
        passwordLabel.setText("Contraseña *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 209, 0, 0);
        jPanel1.add(passwordLabel, gridBagConstraints);

        emailTextField.setToolTipText("");
        emailTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextFieldMousePressed(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 357;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 221, 0, 0);
        jPanel1.add(emailTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(space5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(space6, gridBagConstraints);

        passwordTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextFieldMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 357;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 221, 0, 0);
        jPanel1.add(passwordTextField, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(255, 90, 95));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Acceso");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 99, 0, 0);
        jPanel1.add(loginButton, gridBagConstraints);

        registerLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 90, 95));
        registerLabel.setText("¿No tienes una cuenta?");
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 86, 0, 0);
        jPanel1.add(registerLabel, gridBagConstraints);

        errorLabel.setText("Usuario o contraseña incorrectos.");
        errorLabel.setEnabled(false);
        errorLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 65, 0, 0);
        jPanel1.add(errorLabel, gridBagConstraints);

        statementLabel.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel.setText("Nota: se deben rellenar todos los campos obligatorios (marcados con *)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 252, 0, 0);
        jPanel1.add(statementLabel, gridBagConstraints);

        subtitleLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(255, 90, 95));
        subtitleLabel.setText("Vista al mar o a la montaña: ¡elija usted mismo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 3, 0, 0);
        jPanel1.add(subtitleLabel, gridBagConstraints);

        privacypolicyLabel.setBackground(new java.awt.Color(0, 0, 0));
        privacypolicyLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        privacypolicyLabel.setForeground(new java.awt.Color(255, 70, 70));
        privacypolicyLabel.setText("Política de privacidad");
        privacypolicyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        privacypolicyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                privacypolicyLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 93, 58, 0);
        jPanel1.add(privacypolicyLabel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed

    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMousePressed
        passwordTextField.setText("");
    }//GEN-LAST:event_passwordTextFieldMousePressed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        errorLabel.setVisible(false);
        //Inicializamos atributos
        String correo = emailTextField.getText();

        char[] passwordCharArray = passwordTextField.getPassword();
        String clave = new String(passwordCharArray);
        int tipo = Sesion.iniciarSesion(correo, clave);
        resetText();
        switch (tipo) {
            case 0:
                errorLabel.setVisible(true);
                break;
            case 1:
                System.out.println("Admin");
                App.cardLayout.show(App.cards, "Pantalla adminscreen");
                break;
            case 2:
                System.out.println("Client");
                App.loadMainScreen();
                break;
            case 3:
                System.out.println("Anfitrión");
                App.loadMainScreen();
                break;
            default:
                break;
        }
        
    


    }//GEN-LAST:event_loginButtonActionPerformed

    private void emailTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMousePressed
        emailTextField.setText("");
    }//GEN-LAST:event_emailTextFieldMousePressed

    private void errorLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabelPropertyChange

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseClicked
        resetText();
        App.cardLayout.show(App.cards, "Pantalla register");
    }//GEN-LAST:event_registerLabelMouseClicked

    private void privacypolicyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacypolicyLabelMouseClicked
        App.cardLayout.show(App.cards, "Pantalla privacypolicy");
    }//GEN-LAST:event_privacypolicyLabelMouseClicked

    private void photoLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton photoLabel;
    private javax.swing.JLabel privacypolicyLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel space5;
    private javax.swing.JLabel space6;
    private javax.swing.JLabel statementLabel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
