/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_UX;

import Logica.Anfitrion;
import Logica.Particular;
import Logica.Cliente;
import Logica.Sesion;
import Logica.Tarjeta;
import Logica.Validacion;
import java.time.LocalDate;

public class Register extends javax.swing.JPanel {

    public Register() {
        initComponents();
        errorLabel.setVisible(false);
        errorLabel1.setVisible(false);
        errorLabel2.setVisible(false);
        errorLabel6.setVisible(false);
        errorLabel3.setVisible(false);
        errorLabel8.setVisible(false);
        errorLabel5.setVisible(false);
        errorLabel4.setVisible(false);
        noselectLabel.setVisible(false);
        requirementsLabel.setVisible(false);
        monthTextField.setVisible(false);
        dayTextField.setVisible(false);
        yearTextField.setVisible(false);
        cvvTextField.setVisible(false);
        CCTextField.setVisible(false);

        promocodeTextField.setVisible(false);
        promocodeLabel.setVisible(false);

        CCLabel.setVisible(false);
        dayLabel.setVisible(false);
        monthLabel.setVisible(false);
        yearLabel.setVisible(false);
        cvvLabel.setVisible(false);
        noselectLabel.setVisible(false);
        userExiste.setVisible(false);
        statementLabel.setVisible(false);
    }

    public void resetText() {
        userTextField1.setText("");
        DNITextField.setText("");
        emailTextField.setText("");
        passwordTextField.setText("");
        tlfTextField.setText("");
        CCTextField.setText("");
        cvvTextField.setText("");
        promocodeTextField.setText("");
        monthTextField.setText("");
        dayTextField.setText("");
        yearTextField.setText("");
        selectComboBox.setSelectedItem("Seleccione entre:");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        createaccLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        promocodeTextField = new javax.swing.JTextField();
        promocodeLabel = new javax.swing.JLabel();
        tlfLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        selectComboBox = new javax.swing.JComboBox<>();
        existaccLabel = new javax.swing.JLabel();
        noselectLabel = new javax.swing.JLabel();
        DNILabel = new javax.swing.JLabel();
        DNITextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        tlfTextField = new javax.swing.JTextField();
        dayLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        CCLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();
        errorLabel3 = new javax.swing.JLabel();
        errorLabel8 = new javax.swing.JLabel();
        errorLabel5 = new javax.swing.JLabel();
        errorLabel6 = new javax.swing.JLabel();
        errorLabel2 = new javax.swing.JLabel();
        requirementsLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        cvvTextField = new javax.swing.JTextField();
        CCTextField = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        cvvLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        statementLabel2 = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        statementLabel = new javax.swing.JLabel();
        userExiste = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        userTextField1 = new javax.swing.JTextField();
        errorLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 250, 248));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 250, 248));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        createaccLabel.setBackground(new java.awt.Color(255, 90, 95));
        createaccLabel.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        createaccLabel.setForeground(new java.awt.Color(255, 90, 95));
        createaccLabel.setText("Cree su cuenta en JavaBNB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        jPanel1.add(createaccLabel, gridBagConstraints);

        subtitleLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(255, 90, 95));
        subtitleLabel.setText("Anfitrión o cliente: ¡elija su función!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(subtitleLabel, gridBagConstraints);

        photoLabel.setBackground(new java.awt.Color(255, 90, 95));
        photoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/airbnb logo - 100x100.png"))); // NOI18N
        photoLabel.setBorderPainted(false);
        photoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        photoLabel.setDefaultCapable(false);
        photoLabel.setFocusPainted(false);
        photoLabel.setFocusable(false);
        photoLabel.setRequestFocusEnabled(false);
        photoLabel.setRolloverEnabled(false);
        photoLabel.setVerifyInputWhenFocusTarget(false);
        photoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoLabelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(photoLabel, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("REGISTRO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        promocodeTextField.setToolTipText("");
        promocodeTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        promocodeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        promocodeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                promocodeTextFieldMousePressed(evt);
            }
        });
        promocodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocodeTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 41;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(promocodeTextField, gridBagConstraints);

        promocodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        promocodeLabel.setForeground(new java.awt.Color(102, 102, 102));
        promocodeLabel.setText("Código promocional *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 40;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(promocodeLabel, gridBagConstraints);

        tlfLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tlfLabel.setForeground(new java.awt.Color(102, 102, 102));
        tlfLabel.setText("Teléfono *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(tlfLabel, gridBagConstraints);

        passwordTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextFieldMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(passwordTextField, gridBagConstraints);

        registerButton.setBackground(new java.awt.Color(255, 90, 95));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrarse");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 48;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        jPanel1.add(registerButton, gridBagConstraints);

        selectComboBox.setBackground(new java.awt.Color(255, 90, 95));
        selectComboBox.setForeground(new java.awt.Color(255, 255, 255));
        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione entre:", "Anfitrion", "Particular" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel1.add(selectComboBox, gridBagConstraints);

        existaccLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        existaccLabel.setForeground(new java.awt.Color(255, 90, 95));
        existaccLabel.setText("¿Ya tiene una cuenta?");
        existaccLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        existaccLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existaccLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 49;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 19, 0);
        jPanel1.add(existaccLabel, gridBagConstraints);

        noselectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noselectLabel.setForeground(new java.awt.Color(255, 0, 0));
        noselectLabel.setText("Alguno de los datos no es válido. Rellene todos los campos correctamente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 45;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel1.add(noselectLabel, gridBagConstraints);

        DNILabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DNILabel.setForeground(new java.awt.Color(102, 102, 102));
        DNILabel.setText("DNI *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(DNILabel, gridBagConstraints);

        DNITextField.setToolTipText("");
        DNITextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DNITextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DNITextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DNITextFieldMousePressed(evt);
            }
        });
        DNITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNITextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(DNITextField, gridBagConstraints);

        emailTextField.setToolTipText("");
        emailTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextFieldMousePressed(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(emailTextField, gridBagConstraints);

        tlfTextField.setToolTipText("");
        tlfTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tlfTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tlfTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tlfTextFieldMousePressed(evt);
            }
        });
        tlfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlfTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(tlfTextField, gridBagConstraints);

        dayLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dayLabel.setForeground(new java.awt.Color(102, 102, 102));
        dayLabel.setText("Día:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(dayLabel, gridBagConstraints);

        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(102, 102, 102));
        passLabel.setText("Contraseña *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(passLabel, gridBagConstraints);

        CCLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CCLabel.setForeground(new java.awt.Color(102, 102, 102));
        CCLabel.setText("Tarjeta de crédito *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(CCLabel, gridBagConstraints);

        errorLabel.setText("Seleccione algo, por favor");
        errorLabel.setEnabled(false);
        errorLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabelPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 0, 0);
        jPanel1.add(errorLabel, gridBagConstraints);

        errorLabel1.setText("Esta tarjeta no existe");
        errorLabel1.setEnabled(false);
        errorLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 37;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel1, gridBagConstraints);

        errorLabel3.setText("Contraseña poco segura");
        errorLabel3.setEnabled(false);
        errorLabel3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel3PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel3, gridBagConstraints);

        errorLabel8.setText("Este código promocional no existe");
        errorLabel8.setEnabled(false);
        errorLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel8PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 42;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel8, gridBagConstraints);

        errorLabel5.setText("Formato no válido");
        errorLabel5.setEnabled(false);
        errorLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel5PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel5, gridBagConstraints);

        errorLabel6.setText("Formato no válido");
        errorLabel6.setEnabled(false);
        errorLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel6PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel6, gridBagConstraints);

        errorLabel2.setText("Formato no válido");
        errorLabel2.setEnabled(false);
        errorLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel2PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel2, gridBagConstraints);

        requirementsLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(102, 102, 102));
        requirementsLabel.setText("Al menos una letra mayúscula, minúscula, dígitos y 8 caracteres de longitud");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel1.add(requirementsLabel, gridBagConstraints);

        dayTextField.setToolTipText("");
        dayTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dayTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dayTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dayTextFieldMousePressed(evt);
            }
        });
        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 27, 2, 6);
        jPanel1.add(dayTextField, gridBagConstraints);

        yearTextField.setToolTipText("");
        yearTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yearTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        yearTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yearTextFieldMousePressed(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 204, 2, 0);
        jPanel1.add(yearTextField, gridBagConstraints);

        cvvTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvvTextField.setToolTipText("");
        cvvTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cvvTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cvvTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvvTextFieldMousePressed(evt);
            }
        });
        cvvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 352, 2, 0);
        jPanel1.add(cvvTextField, gridBagConstraints);

        CCTextField.setToolTipText("");
        CCTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CCTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CCTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CCTextFieldMousePressed(evt);
            }
        });
        CCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(CCTextField, gridBagConstraints);

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthLabel.setForeground(new java.awt.Color(102, 102, 102));
        monthLabel.setText("Mes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 80, 0, 30);
        jPanel1.add(monthLabel, gridBagConstraints);

        yearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(102, 102, 102));
        yearLabel.setText("Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 171, 0, 0);
        jPanel1.add(yearLabel, gridBagConstraints);

        cvvLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cvvLabel.setForeground(new java.awt.Color(102, 102, 102));
        cvvLabel.setText("CVV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 315, 0, 0);
        jPanel1.add(cvvLabel, gridBagConstraints);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(102, 102, 102));
        emailLabel.setText("Correo *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 30);
        jPanel1.add(emailLabel, gridBagConstraints);

        statementLabel2.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel2.setText("Nota: se deben rellenar todos los campos obligatorios (marcados con *)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 44;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel1.add(statementLabel2, gridBagConstraints);

        monthTextField.setToolTipText("");
        monthTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        monthTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthTextFieldMousePressed(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 113, 2, 0);
        jPanel1.add(monthTextField, gridBagConstraints);

        statementLabel.setForeground(new java.awt.Color(102, 102, 102));
        statementLabel.setText("Introduzca la fecha de caducidad y el CVV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        jPanel1.add(statementLabel, gridBagConstraints);

        userExiste.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userExiste.setForeground(new java.awt.Color(0, 153, 51));
        userExiste.setText("Ya existe una cuenta asociada a este teléfono, DNI o correo. Por favor, inicie sesión.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 47;
        jPanel1.add(userExiste, gridBagConstraints);

        userLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel1.setForeground(new java.awt.Color(102, 102, 102));
        userLabel1.setText("Nombre completo *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel1.add(userLabel1, gridBagConstraints);

        userTextField1.setToolTipText("");
        userTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextField1MousePressed(evt);
            }
        });
        userTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 354;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 2, 0);
        jPanel1.add(userTextField1, gridBagConstraints);

        errorLabel4.setText("Formato no válido");
        errorLabel4.setEnabled(false);
        errorLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                errorLabel4PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(errorLabel4, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void promocodeTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promocodeTextFieldMousePressed
    }//GEN-LAST:event_promocodeTextFieldMousePressed

    private void promocodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocodeTextFieldActionPerformed

    }//GEN-LAST:event_promocodeTextFieldActionPerformed

    private void passwordTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMousePressed
    }//GEN-LAST:event_passwordTextFieldMousePressed

    // Este método validará todos los campos introducidos, mostrando los mensajes de error correspondientes si
    // encuentra algún dato no válido o registrando al cliente si todos son correctos.
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        //Inicializamos atributos
        String nombre = userTextField1.getText();
        String dni = DNITextField.getText();
        String correo = emailTextField.getText();

        String fotografia = ".\\src\\main\\resources\\fotosperfil\\user (2).jpg";

        char[] passwordCharArray = passwordTextField.getPassword();
        String clave = new String(passwordCharArray);
        String telefono = tlfTextField.getText();
        String numtarjeta = CCTextField.getText();
        String cvv = cvvTextField.getText();
        String promocode = promocodeTextField.getText();
        double saldo = 1000; //el saldo inicial de todos los clientes será de 1000
        boolean valido = true;
        userExiste.setVisible(false);
        int dia = -1;
        int mes = -1;
        int año = -1;

        if (!Validacion.validarNombre(nombre)) {
            errorLabel4.setVisible(true);
            valido = false;
            promocodeTextField.setText("");
        } else {
            errorLabel4.setVisible(false);
        }

        if (!Validacion.validarDNI(dni)) {
            errorLabel2.setVisible(true);
            valido = false;
            DNITextField.setText("");
        } else {
            errorLabel2.setVisible(false);
        }

        if (!Validacion.validarEmail(correo)) {
            errorLabel6.setVisible(true);
            valido = false;
            emailTextField.setText("");
        } else {
            errorLabel6.setVisible(false);
        }

        if (!Validacion.validarTelefono(telefono)) {
            errorLabel5.setVisible(true);
            valido = false;
            tlfTextField.setText("");
        } else {
            errorLabel5.setVisible(false);
        }

        if (!Validacion.validarContraseña(clave)) {
            errorLabel3.setVisible(true);
            requirementsLabel.setVisible(true);
            passwordTextField.setText("");
            valido = false;
        } else {
            errorLabel3.setVisible(false);
        }

        String selectedOption = (String) selectComboBox.getSelectedItem();
        boolean usuarioExiste = Validacion.comprobarExistenciaCliente(correo.toLowerCase(), dni, telefono);

        if (selectedOption.equals("Seleccione entre:")) {
            noselectLabel.setVisible(true);
            userExiste.setVisible(false);

        } else if (usuarioExiste) {
            userExiste.setVisible(true);
            noselectLabel.setVisible(false);

        } else if (selectedOption.equals("Anfitrion") && valido) {
            noselectLabel.setVisible(false);
            Anfitrion nuevoAnfitrion = new Anfitrion(dni, nombre, correo.toLowerCase(), clave, telefono);
            nuevoAnfitrion.setFotoperfil(fotografia); // Establecer la fotografía del perfil
            Sesion.registrarCliente(nuevoAnfitrion);
            resetText();
            App.loadMainScreen();
        } else if (selectedOption.equals("Anfitrion") && !valido) {
            noselectLabel.setVisible(true);

        } else if (selectedOption.equals("Particular")) {
            try {
                if (!monthTextField.getText().isEmpty()) {
                    mes = Integer.parseInt(monthTextField.getText());
                } else {
                    System.err.println("El campo de día está vacío.");
                }

                if (!dayTextField.getText().isEmpty()) {
                    dia = Integer.parseInt(dayTextField.getText());
                } else {
                    System.err.println("El campo de mes está vacío.");
                }

                if (!yearTextField.getText().isEmpty()) {
                    año = Integer.parseInt(yearTextField.getText());
                } else {
                    System.err.println("El campo de año está vacío.");
                }

            } catch (NumberFormatException e) {
                System.err.println("Error al convertir el texto a número.");
                dia = -1;
                mes = -1;
                año = -1;
            }

            if (!Validacion.validarTarjeta(numtarjeta, dia, mes, año, cvv)) {
                errorLabel1.setVisible(true);
                valido = false;
                monthTextField.setText("");
                dayTextField.setText("");
                yearTextField.setText("");
                cvvTextField.setText("");
            } else {

                errorLabel1.setVisible(false);
            }

            if (!Validacion.validarPromocode(promocode)) {
                errorLabel8.setVisible(true);
                promocodeTextField.setText("");
                valido = false;
            } else {
                errorLabel8.setVisible(false);
            }
            if (valido) {
                noselectLabel.setVisible(false);

                boolean vip = Validacion.validarVipPromocode(promocode);
                LocalDate fechaCaducidad = LocalDate.of(año, mes, dia);
                Tarjeta tarjeta = new Tarjeta(nombre, numtarjeta, dia, mes, año, fechaCaducidad, cvv, saldo);
                Particular nuevoParticular = new Particular(tarjeta, vip, dni, nombre, correo.toLowerCase(), clave, telefono);
                nuevoParticular.setFotoperfil(fotografia); // Establecer la fotografía del perfil
                Sesion.registrarCliente(nuevoParticular);
                resetText();
                App.loadMainScreen();
                return;
            }
            noselectLabel.setVisible(true);

        }


    }//GEN-LAST:event_registerButtonActionPerformed

    private void existaccLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existaccLabelMouseClicked
        resetText();
        App.cardLayout.show(App.cards, "Pantalla login");
    }//GEN-LAST:event_existaccLabelMouseClicked

    private void tlfTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlfTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldMousePressed

    private void tlfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlfTextFieldActionPerformed

    private void DNITextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DNITextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldMousePressed

    private void DNITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNITextFieldActionPerformed

    private void emailTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldMousePressed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void errorLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabelPropertyChange

    private void errorLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel1PropertyChange

    private void errorLabel3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel3PropertyChange

    private void errorLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel8PropertyChange

    private void errorLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel5PropertyChange

    private void errorLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel6PropertyChange

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        //Qué ocurre al elegir una opción u otra
        String selectedOption = (String) selectComboBox.getSelectedItem();
        if (selectedOption.equals("Particular")) {
            monthTextField.setVisible(true);
            dayLabel.setVisible(true);
            dayTextField.setVisible(true);
            monthLabel.setVisible(true);
            yearTextField.setVisible(true);
            yearLabel.setVisible(true);
            cvvTextField.setVisible(true);
            cvvLabel.setVisible(true);
            promocodeTextField.setVisible(true);

            CCTextField.setVisible(true);
            CCLabel.setVisible(true);
            noselectLabel.setVisible(true);
            statementLabel.setVisible(true);
            promocodeLabel.setVisible(true);
            noselectLabel.setVisible(false);

        } else {
            monthTextField.setVisible(false);
            dayLabel.setVisible(false);
            dayTextField.setVisible(false);
            monthLabel.setVisible(false);
            yearTextField.setVisible(false);
            yearLabel.setVisible(false);
            cvvTextField.setVisible(false);
            cvvLabel.setVisible(false);
            CCTextField.setVisible(false);
            CCLabel.setVisible(false);

            promocodeLabel.setVisible(false);
            promocodeTextField.setVisible(false);

            noselectLabel.setVisible(false);

            errorLabel.setVisible(false);
            errorLabel1.setVisible(false);
            errorLabel2.setVisible(false);
            errorLabel6.setVisible(false);
            errorLabel3.setVisible(false);
            errorLabel8.setVisible(false);
            errorLabel5.setVisible(false);
            statementLabel.setVisible(false);
            errorLabel4.setVisible(false);

        }

    }//GEN-LAST:event_selectComboBoxActionPerformed

    private void errorLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel2PropertyChange

    private void yearTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldMousePressed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void cvvTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldMousePressed

    private void cvvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvTextFieldActionPerformed

    private void CCTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldMousePressed

    private void CCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCTextFieldActionPerformed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void dayTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldMousePressed

    private void monthTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthTextFieldMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldMousePressed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void userTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1MousePressed

    private void userTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextField1ActionPerformed

    private void errorLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_errorLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_errorLabel4PropertyChange

    private void photoLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTextField CCTextField;
    private javax.swing.JLabel DNILabel;
    private javax.swing.JTextField DNITextField;
    private javax.swing.JLabel createaccLabel;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField cvvTextField;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JLabel errorLabel2;
    private javax.swing.JLabel errorLabel3;
    private javax.swing.JLabel errorLabel4;
    private javax.swing.JLabel errorLabel5;
    private javax.swing.JLabel errorLabel6;
    private javax.swing.JLabel errorLabel8;
    private javax.swing.JLabel existaccLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel noselectLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton photoLabel;
    private javax.swing.JLabel promocodeLabel;
    private javax.swing.JTextField promocodeTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JComboBox<String> selectComboBox;
    private javax.swing.JLabel statementLabel;
    private javax.swing.JLabel statementLabel2;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel tlfLabel;
    private javax.swing.JTextField tlfTextField;
    private javax.swing.JLabel userExiste;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JTextField userTextField1;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
